In [43]:
import numpy as np

In [141]:
class create_dataset():
    """ create the 2 XOR datasets, X & Y, for the DNN model """
    
    # create the entry dataset X
    def create_X(self, X_size):
        self.X = np.random.randint(2, size=(2, X_size))
        return self.X
    
    # create the label dataset Y
    def create_Y(self, X):
        self.Y = np.sum(X, axis=0)
        self.Y[self.Y != 1] = 0
        return self.Y

In [102]:
class activation_fn():
    """ define activation functions that will be needed in the DNN"""
    
    # sigmoid function and its derivative
    def sigmoid(self, Z=None, A=None, derivative=False):
        if derivative:
            return A * (1 - A)
        else:
            return 1 / (1 + np.exp(-Z))
        
    # tanh function and its derivative
    def tanh(self, Z=None, A=None, derivative=False):
        if derivative:
            return 1 - np.square(A)
        else:
            return (np.exp(Z) - np.exp(-Z)) / (np.exp(Z) + np.exp(-Z))
    
    # relu function and its derivative
    def relu(self, Z, derivative=False):
        if derivative:
            return (Z > 0) * 1
        else:
            return (Z > 0) * Z

In [146]:
ds = create_dataset()
X_size = 4
X = ds.create_X(X_size)
print(X)
Y = ds.create_Y(X)
print(Y)

[[1 0 1 1]
 [0 1 1 0]]
[1 1 0 1]


In [114]:
X_size = 4
X = np.random.randint(2, size=(2,X_size))
print(X)
print(type(X))
Y = np.sum(X, axis=0)
print(Y)
print((Y != 1))
Y[Y != 1] = 0
print(Y)

[[1 1 0 0]
 [0 1 1 0]]
<class 'numpy.ndarray'>
[1 2 1 0]
[False  True False  True]
[1 0 1 0]


In [109]:
test = activation_fn()
test.relu(X)

array([[1, 1, 0, 0],
       [0, 0, 1, 1]])

In [101]:
test.relu(X, derivative=True)

array([[1, 0, 0, 0],
       [1, 1, 1, 0]])