In [43]:
import numpy as np

In [155]:
class CreateDataset:
    """ create the 2 XOR datasets, X & Y, for the DNN model """
    
    # create the entry dataset X
    def create_X(self, X_size):
        self.X = np.random.randint(2, size=(2, X_size))
        return self.X
    
    # create the label dataset Y
    def create_Y(self, X):
        self.Y = np.sum(X, axis=0)
        self.Y[self.Y != 1] = 0
        return self.Y

In [156]:
class ActivationFN:
    """ define activation functions that will be needed in the DNN"""
    
    # sigmoid function and its derivative
    def sigmoid(self, Z=None, A=None, derivative=False):
        if derivative:
            return A * (1 - A)
        else:
            return 1 / (1 + np.exp(-Z))
        
    # tanh function and its derivative
    def tanh(self, Z=None, A=None, derivative=False):
        if derivative:
            return 1 - np.square(A)
        else:
            return (np.exp(Z) - np.exp(-Z)) / (np.exp(Z) + np.exp(-Z))
    
    # relu function and its derivative
    def relu(self, Z, derivative=False):
        if derivative:
            return (Z > 0) * 1
        else:
            return (Z > 0) * Z

In [165]:
class Layer:
    """ initial class to initialize parameters and ??? """
    
    # initialize parameters
    def __init__(self, layer_b4, layer_after):
        
#         self.L = len(layer_dim)
        
#         for i in range(1, self.L):
#         self.W = np.random.randn(layer_dim[i], layer_dim[i-1])
#         self.b = np.zeros(layer_dim[i], 1)

        self.W = np.random.randn(layer_after, layer_b4) * 0.01
        self.b = np.zeros((layer_after, 1))
        print(self.W)
        print(self.b)
    
    # calculate forward pass: linear fn (Z = WX + b) and non-linear (A = g(Z))
#     def forward_pass(self, X):
#         self.Z = 
    

In [166]:
layer = Layer(3, 4)

[[ 0.00358662 -0.01850868 -0.00114098]
 [ 0.00690415 -0.00860543 -0.00789455]
 [ 0.01557924  0.00708046 -0.01370354]
 [ 0.01362968 -0.0004657   0.01262541]]
[[0.]
 [0.]
 [0.]
 [0.]]


In [157]:
ds = CreateDataset()
X_size = 4
X = ds.create_X(X_size)
print(X)
Y = ds.create_Y(X)
print(Y)

[[1 0 1 0]
 [1 1 1 0]]
[0 1 0 0]


In [150]:
X_size = 4
X = np.random.randint(2, size=(2,X_size))
print(X)
print(type(X))
Y = np.sum(X, axis=0)
print(Y)
print((Y != 1))
Y[Y != 1] = 0
print(Y)

[[0 1 1 0]
 [1 0 1 1]]
<class 'numpy.ndarray'>
[1 1 2 1]
[False False  True False]
[1 1 0 1]


In [151]:
test = ActivationFN()
test.relu(X)

array([[0, 1, 1, 0],
       [1, 0, 1, 1]])

In [152]:
test.relu(X, derivative=True)

array([[0, 1, 1, 0],
       [1, 0, 1, 1]])

In [153]:
np.random.rand(4,3)

array([[0.87558993, 0.93684569, 0.94847332],
       [0.96739116, 0.23928585, 0.85061525],
       [0.06319912, 0.46525894, 0.21063519],
       [0.9365597 , 0.49253958, 0.06764355]])